application: kegstart
version: 0-1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /(.*\.(css|html|js))$
  static_files: static/\1
  upload: static/.*\.(css|html|js)$

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.1"